name: merge

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Build
        run: go build

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}